--- #YAML:1.0
name:                Apache2-checkReferer
version:             0.02
abstract:            Prevent most "deep linking"
license:             ~
author:              
    - Henk van Oers <hvo.pm@xs4all.nl>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Apache2::Connection:           
    Apache2::Const:                
    Apache2::Log:                  
    Apache2::RequestRec:           
    Apache2::RequestUtil:          
    Test::More:                    
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
